application: sc2jsonhunt
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /lib
  static_dir: static/lib

- url: /partials
  static_dir: static/partials

- url: /stylesheets
  static_dir: static/stylesheets

- url: /index.html
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /.*
  script: handlers.app
